name: e2e-tests-workflow

on: push

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create .env
        run: touch .env && echo 'RESEND_API_KEY = ${{secrets.SECRET_RESEND_API_KEY}}' >> .env && echo 'URL_CONFIRMATION_PAGE = ${{secrets.SECRET_URL_CONFIRMATION_PAGE}}' >> .env && echo 'JWT_TOKEN_KEY = ${{secrets.SECRET_JWT_TOKEN_KEY}}' >> .env  
      - name: Launch e2e tests
        run: docker compose -f docker-compose.e2e.yml up --build --exit-code-from=e2e