name: client-tests-workflow

on: pull_request

env:
  CI: CI

jobs:
  test-client:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ vars.POSTGRES_USERNAME }}
          POSTGRES_DB: ${{ vars.POSTGRES_DATABASE }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create .env
        run: cp .env.example .env
      - name: Install backend
        run: cd backend && npm ci && npm run start
      - name: Goto frontend and run tests
        run: cd frontend && npm ci && npm run start && npm run test
