name: client-tests-workflow

on: push

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run docker
        run: docker compose up --build --exit-code-from=frontend
      - name: Goto frontend and run tests
        run: cd frontend && npm run test