name: client-tests-workflow

on: pull_request

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create .env
        run: cp .env.example .env
      - name: Run docker
        run: docker compose up --build --exit-code-from frontend && cd frontend && npm run test
      - name: Goto frontend and run tests
        run: cd frontend && npm run test

        - name: Integration tests
        run: docker-compose up --exit-code-from integrationtest integrationtest